server:
  port: 8080
spring:
  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    host: smtp.163.com
    #发送者邮箱
    username: jkddg2022@163.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: NSIBHNDQFGODUHTM
    #端口号465或587
    port: 25
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
sender-email:
  configs:
    mail-0:
      host: smtp.163.com
      port: 25
      username: jkddg2023@163.com
      password: BYLQSOKYREAVFKJT
      senderName: jkddg2023@163.com
    mail-1:
      host: smtp.163.com
      port: 25
      username: jkddg2024@163.com
      password: IFSMYCDVPLHNQZOU
      senderName: jkddg2024@163.com
    mail-2:
      host: smtp.163.com
      port: 25
      username: jkddg2025@163.com
      password: KGDJGNDISLTUMVSW
      senderName: jkddg2025@163.com
    mail-3:
      host: smtp.163.com
      port: 25
      username: jkddg2026@163.com
      password: EWDYPFNBDZBEITWV
      senderName: jkddg2026@163.com
    mail-4:
      host: smtp.163.com
      port: 25
      username: jkddg2027@163.com
      password: PKXARZXXFKUPEGAY
      senderName: jkddg2027@163.com
    mail-5:
      host: smtp.163.com
      port: 25
      username: jkddg2028@163.com
      password: CNVKJSFRLAZEIDFU
      senderName: jkddg2028@163.com

nvr:
  linux-lib-path: /home/javaApps/hklib/
  linux-sdk-log: /home/javaApps/nvrMailApp/sdkLog
  win-lib-path: D:\hklib\
  win-sdk-log: D:\sdkLog
  server:
    ip: 192.168.8.114 #192.168.8.114
    port: 8000
    user: admin
    pwd: abcd123456

  capture:
    in-memory: true
    folder-win: d:\capture\
    folder-linux: /home/javaApps/capture/
    #当图像压缩分辨率为VGA时，支持0=CIF, 1=QCIF, 2=D1抓图，
    #	当分辨率为3=UXGA(1600x1200), 4=SVGA(800x600), 5=HD720p(1280x720),6=VGA,7=XVGA, 8=HD900p
    #	仅支持当前分辨率的抓图
    pic-size: 5
    sleep-second: 3
    pic-quality: 1
    default-capture-interval-second: 60
    mail-capture-interval: "03:30-07:30-180,17:00-22:00-180"
    ftp-capture-interval: "03:30-07:30-60,17:00-22:00-60"
    find-people: true
  channel:
    flash-minute: 1

  alarm:
    interval-second: 30
    mail-interval-second: 150
    capture-count: 1
    channel-name: 前门,内院
  mail-to: jkddg2022@163.com

#ftp服务器ip
ftp:
  host: jkddg.cn
  #ftp端口号
  port: 8021
  #ftp请求的用户名
  username: ftpUser
  #ftp请求的密码
  password: jkddg123456